djangoProject2/urls.py
# from django.contrib import admin
from django.contrib import admin
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView, TokenVerifyView

from auth_user.serializers import CustomTokenRefreshSerializer, CustomTokenObtainPairSerializer
from auth_user.views import register, CustomAuthToken
from auth_user.views import login_view
from auth_user.views import home_view
from django.urls import include, path

from russianNews import views


urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),


    path('news/', views.news_list, name='news_list'),

    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('token/create', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path("token/verify", TokenVerifyView.as_view(), name="token_verify"),
    path('delete-comment/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('search/', views.search_feed, name='search_feed'),
    path('api/v1/executeCommand', views.execute_command, name='execute_command'),
    path('api/v1/getcurrency', views.getCurrency, name='getCurrency'),
    path('get-image/', views.get_image, name='get_image'),
    path('logs/', views.display_logs, name='display_logs'),
    path('i18n/', include('django.conf.urls.i18n'))
]

russianNews/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    ADMIN = 'admin'
    USER = 'user'
    ROLE_CHOICES = [
        (ADMIN, 'Admin'),
        (USER, 'User'),
    ]

    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    username = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=USER)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name="user_set_custom",  # Custom related_name
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name="user_set_custom",  # Custom related_name
        help_text='Specific permissions for this user.',
    )

    def __str__(self):
        return self.username

    def get_full_name(self):
        return f"{self.firstname} {self.lastname}"

    def get_short_name(self):
        return self.firstname

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'


class NewsItem(models.Model):
    title_en = models.CharField(max_length=200)
    title_ru = models.CharField(max_length=200)

    link = models.URLField()

    description_en = models.TextField()
    description_ru = models.TextField()

    category_en = models.CharField(max_length=100)
    category_ru = models.CharField(max_length=100)

    pub_date = models.DateTimeField()


class Comment(models.Model):
    news_item = models.ForeignKey(NewsItem, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.news_item.title_en}"


class LastFetch(models.Model):
    last_fetched = models.DateTimeField(default=timezone.now)



class LogEntry(models.Model):
    ATTACK_TYPES = [
        ('PS', 'Port Scan'),
        ('ID', 'Information Disclosure'),
        ('RCE', 'Remote Code Execution'),
        ('OTH', 'Other')
    ]
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=255, null=True)
    ip_address = models.GenericIPAddressField(null=True)
    user_agent = models.TextField(null=True)
    absolute_uri = models.URLField(null=True)
    http_method = models.CharField(max_length=10, null=True)
    input = models.CharField(max_length=255, null=True)

    attackType = models.CharField(max_length=3, choices=ATTACK_TYPES, blank=True, null=True)

    def __str__(self):
        return f"{self.created_at} - {self.user} - {self.action}"

russianNews/forms.py
from django import forms

from russianNews.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class ImageUrlForm(forms.Form):
    image_url = forms.URLField(label='Enter the Image URL')

russianNews/views.py
from .forms import ImageUrlForm
import subprocess
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse
from django.http import HttpResponse
from django.shortcuts import render
import logging
import time

import feedparser
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from requests import ReadTimeout
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication
from django import forms

from .forms import CommentForm
from .models import Comment, LogEntry
from russianNews.models import NewsItem, LastFetch
from django.utils.dateparse import parse_datetime
import requests
from russianNews.models import User
import xml.etree.ElementTree as Et
from dateutil import parser
from googletrans import Translator
import logging

logger = logging.getLogger(__name__)


def news_list(request):
    """
    View to display a list of news items.
    """
    # fetch_news()

    #fetch_news()

    # Get the search query from the URL query parameter
    search_query = request.GET.get('search', '')

    if search_query:
        logger.info('Searched a news', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'OTH'

        })
        news_items = NewsItem.objects.filter(
            Q(title_en__icontains=search_query) |
            Q(title_ru__icontains=search_query) |
            Q(description_en__icontains=search_query) |
            Q(description_ru__icontains=search_query)
        ).order_by('-pub_date')
    else:

        logger.info('List the news', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'OTH'

        })
        news_items = NewsItem.objects.all().order_by('-pub_date')

    return render(request, 'news_list.html', {'news_items': news_items, 'search_query': search_query})


def translate_text_with_retry(text, src, dest, max_retries=3):
    translator = Translator()
    for attempt in range(max_retries):
        try:
            return translator.translate(text, src=src, dest=dest).text
        except ReadTimeout:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
                continue
            else:

                return text


def fetch_news():
    feed_url = 'https://www.mk.ru/rss/news/index.xml'
    xml = getXML(feed_url)
    last_build, items = extract_items_and_lbd(xml)

    for entry in items:
        if not NewsItem.objects.filter(link=entry["link"]).exists():
            pub_date_parsed = parser.parse(entry.get("pub_date"))

            title_ru = entry.get("title")
            title_en = translate_text_with_retry(title_ru, src='ru', dest='en')

            link = entry.get("link")
            desc_ru = entry.get("description")
            desc_en = translate_text_with_retry(desc_ru, src='ru', dest='en')

            pub_date = pub_date_parsed

            category_ru = entry.get("category")
            category_en = translate_text_with_retry(
                category_ru, src='ru', dest='en')

            news_item = NewsItem(
                title_ru=title_ru,
                title_en=title_en,
                link=link,
                description_ru=desc_ru,
                description_en=desc_en,
                pub_date=pub_date,
                category_ru=category_ru,
                category_en=category_en
            )
            news_item.save()


def getXML(url):
    try:

        response = requests.get(url, timeout=100)
        if response.status_code == 200:
            return response.text
        else:
            print(f"Failed to fetch data. Status code: {response.status_code}")
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")


def extract_items_and_lbd(xml_data):
    root = Et.fromstring(xml_data)

    # Initialize a list to store news_item objects
    news_items = []
    lastBuildDate = root.find('.//lastBuildDate').text
    # Iterate through the 'item' elements in the XML
    for item_elem in root.findall('.//item'):
        title = item_elem.find('title').text
        link = item_elem.find('link').text
        description = item_elem.find('description').text
        pub_date = item_elem.find('pubDate').text
        category = item_elem.find('category').text

        # Create a news_item dictionary
        news_item = {
            'title': title,
            'link': link,
            'description': description,
            'pub_date': pub_date,
            'category': category

        }

        # Append the news_item to the list
        news_items.append(news_item)

    return lastBuildDate, news_items


@login_required
def news_detail(request, pk):
    news_item = get_object_or_404(NewsItem, pk=pk)
    if request.method == 'POST':

        logger.info('Made a comment', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'OTH'

        })
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.news_item = news_item
            comment.author = request.user
            comment.save()
            return redirect('news_detail', pk=news_item.pk)
    else:
        form = CommentForm()
    return render(request, 'news_detail.html', {'news_item': news_item, 'form': form})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Check if the user is authorized to delete the comment
    if request.user == comment.author or request.user.is_staff:

        logger.info('Deleted a comment', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'OTH'

        })
        comment.delete()
        return redirect('news_detail', pk=comment.news_item.id)
    else:

        logger.info('Unauthorized comment delete attempt', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'OTH'

        })
        messages.error(
            request, "You do not have permission to delete this comment.")
        return redirect('news_detail', pk=comment.news_item.id)


@login_required
@user_passes_test(lambda u: u.is_staff)
def manage_users(request):
    users = User.objects.all()

    if request.method == "POST" and 'delete_user' in request.POST:
        user_id = request.POST.get('delete_user')
        user_to_delete = User.objects.get(id=user_id)

        if user_to_delete.role == "user":

            logger.info('User delete action', extra={
                'user': request.user,
                'ip_address': request.META.get('REMOTE_ADDR'),
                'user_agent': request.META.get('HTTP_USER_AGENT', ''),
                'absolute_uri': request.build_absolute_uri(),
                'http_method': request.method,
                'attackType': 'OTH'

            })
            user_to_delete.delete()

        else:

            logger.info('Unauthorized user delete action tried.', extra={
                'user': request.user,
                'ip_address': request.META.get('REMOTE_ADDR'),
                'user_agent': request.META.get('HTTP_USER_AGENT', ''),
                'absolute_uri': request.build_absolute_uri(),
                'http_method': request.method,
                'attackType': 'OTH'

            })
            pass


        return redirect('manage_users')

    return render(request, 'manage_users.html', {'users': users})


def search_feed(request):
    feed_url = request.GET.get('feed', '')
    if feed_url:
        logger.info('Feed suggestion submitted.', extra={
            'user': request.user,
            'ip_address': request.META.get('REMOTE_ADDR'),
            'user_agent': request.META.get('HTTP_USER_AGENT', ''),
            'absolute_uri': request.build_absolute_uri(),
            'http_method': request.method,
            'attackType': 'ID',
            'input': feed_url

        })
        try:
            response = requests.get(feed_url) # Vulnerable line to SSRF
            if response.status_code == 200:

                return JsonResponse(response.text, safe=False)
            else:

                return JsonResponse({'error': 'Failed to fetch data from the feed', 'status_code': response.status_code}, status=response.status_code)
        except requests.RequestException as e:

            return JsonResponse({'error': str(e)}, status=500)
    else:
        return JsonResponse({'error': 'No feed URL provided'}, status=400)


@require_http_methods(["GET"])
def execute_command(request):
    try:
        command = request.GET.get('command', '')

        if command:
            process = subprocess.Popen(

russianNews/templates/feed_display.html
<!DOCTYPE html>
<html>
<head>
    <title>Feed Display</title>
</head>
<body>
    <h1>Feed Display</h1>
    {% if data %}
        <p>Feed Data: {{ data|safe }}</p>
    {% else %}
        <p>No data to display.</p>
    {% endif %}
</body>
</html>

russianNews/templates/fetch_image.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fetch Image</title>
</head>
<body>
<div style="margin-bottom: 20px;">
    <a href="{% url 'news_list' %}"
       style="background-color: #0275d8; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; display: inline-block;">
        <- {% trans 'All News' %}
    </a>
</div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Fetch Image</button>
</form>
{% if last_message %}
    <p>{{ last_message }}</p>
{% endif %}
{% if image_url %}
    <img src="{{ image_url }}" alt="{{ response }}" style="max-width: 100%;">
{% elif status_message %}
    <p>{{ status_message }}</p>
{% elif error_message %}
    <p>{{ error_message }}</p>
{% endif %}


</body>
</html>

russianNews/templates/logs_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log Monitoring</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h2>Log Monitoring</h2>
    <table>
        <tr>
            <th>Timestamp</th>
            <th>User</th>
            <th>Action</th>
            <th>IP Address</th>
            <th>User Agent</th>
            <th>URI</th>
            <th>HTTP Method</th>
            <th>Input</th>
            <th>Attack Type</th>
        </tr>
        {% for log in logs %}
        <tr>
            <td>{{ log.created_at }}</td>
            <td>{{ log.user }}</td>
            <td>{{ log.action }}</td>
            <td>{{ log.ip_address }}</td>
            <td>{{ log.user_agent }}</td>
            <td>{{ log.absolute_uri }}</td>
            <td>{{ log.http_method }}</td>
            <td>{{ log.input }}</td>
            <td>{{ log.get_attackType_display }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="9">No logs found.</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

russianNews/templates/manage_users.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Manage Users' %} </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #0275d8;
            color: white;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        button {
            background-color: #d9534f;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 4px;
            font-size: 0.9em;
        }

        button:hover {
            background-color: #c9302c;
        }

        .form-delete {
            margin: 0;
        }
    </style>
</head>
<body>
<h1>{% trans 'Manage Users' %} </h1>

<table>
    <tr>
        <th>{% trans 'Username' %} </th>
        <th>{% trans 'First Name' %}</th>
        <th>{% trans 'Last Name' %}</th>
        <th>{% trans 'Role' %}</th>
        <th></th>
    </tr>
    {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.firstname }}</td>
            <td>{{ user.lastname }}</td>
            <td>{{ user.role }}</td>
            <td>
                {% if user.role == "user" %}
                    <form method="post" class="form-delete">
                        {% csrf_token %}
                        <button type="submit" name="delete_user" value="{{ user.id }}">{% trans 'Delete' %}</button>
                    </form>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>

<h2>{% trans 'Add New User' %}</h2>
<form method="post" action="{% url 'register' %}">
    {% csrf_token %}
    <label for="username">{% trans 'Username' %}</label>
    <input type="text" id="username" name="username" required>

    <label for="firstname">{% trans 'First Name' %}</label>
    <input type="text" id="firstname" name="fname">

    <label for="lastname">{% trans 'Last Name' %}</label>
    <input type="text" id="lastname" name="lname">

    <label for="password">{% trans 'Password' %}</label>
    <input type="password" id="password" name="password" required>
    <label for="role">{% trans 'Role' %}</label>
    <select id="role" name="role">
        <option value="user">{% trans 'User' %}</option>
        <option value="admin">{% trans 'Admin' %}</option>
    </select>

    <button type="submit" >{% trans 'Add User' %}</button>
</form>
</body>
</html>

russianNews/templates/news_detail.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'News Detail' %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 20px auto;
            background-color: white;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1, h2 {
            color: #333;
        }

        .news-content, .comments-section {
            margin-top: 20px;
        }

        .comment {
            border-top: 1px solid #ddd;
            padding: 10px 0;
        }

        .comment:first-child {
            border-top: none;
        }

        .comment-author {
            font-weight: bold;
        }

        .comment-content {
            margin-top: 5px;
        }

        .comment-date {
            font-size: 0.8em;
            color: #999;
        }

        form {
            margin-top: 20px;
        }

        input, textarea, button {
            width: 100%;
            margin: 5px 0;
            padding: 10px;
        }

        button {
            background-color: #0275d8;
            color: white;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background-color: #025aa5;
        }

        .delete-button {
            background-color: #d9534f;
            color: white;
            border: none;
            padding: 5px 10px;
            font-size: 0.8em;
            cursor: pointer;
        }

        .delete-button:hover {
            background-color: #c9302c;
        }
    </style>
</head>
<body>
<div class="container">

    <div style="margin-bottom: 20px;">
        <a href="{% url 'news_list' %}" style="background-color: #0275d8; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; display: inline-block;">
            <- {% trans 'All News' %}
        </a>
    </div>

    <h1>
        {% if request.LANGUAGE_CODE == "en" %}
            {{ news_item.title_en }}
        {% else %}
            {{ news_item.title_ru }}
        {% endif %}
    </h1>
    <div class="news-content">
        <p>
            {% if request.LANGUAGE_CODE == "en" %}
                {{ news_item.description_en }}
            {% else %}
                {{ news_item.description_ru }}
            {% endif %}
        </p>
    </div>

    <div class="comments-section">
        <h2>{% trans 'Comments' %}</h2>
        {% for comment in news_item.comments.all %}
            <div class="comment">
                <span class="comment-author">{{ comment.author.username }}</span>
                <span class="comment-date">{{ comment.created_at|date:"d.m.Y H:i" }}</span>
                <p class="comment-content">{{ comment.content }}</p>

                {% if request.user == comment.author or request.user.is_staff %}
                    <form action="{% url 'delete_comment' comment.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="delete-button">{% trans 'Delete' %}</button>
                    </form>
                {% endif %}
            </div>
        {% empty %}
            <p>{% trans 'No comments yet.' %}</p>
        {% endfor %}
    </div>

    <form method="post">
        {% csrf_token %}
        <textarea name="content" placeholder="{% trans 'Add a comment...' %}"></textarea>
        <button type="submit">{% trans 'Post Comment' %}</button>

    </form>


    <div style="margin-bottom: 20px;">
        <a href="{% url 'get_image' %}"
           style="background-color: #0275d8; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; display: inline-block;">
            -> {% trans 'Upload an image about this news' %}
        </a>
    </div>
</div>
</body>
</html>

russianNews/templates/search_form.html
<!DOCTYPE html>
<html>
<head>
    <title>News Feed Search</title>
</head>
<body>
    <h1>News Feed Search</h1>
    <form action="/search/" method="get">
        <label for="feed">Enter a news feed to be displayed:</label><br>
        <input type="text" id="feed" name="feed"><br>
        <input type="submit" value="Search">
    </form>
    <h1>   {{ data }} </h1>
</body>
</html>